image:
  fullOverride: docker.gitea.com/gitea:28.0.0-rootless@sha256:c168e7ccb767164793a67e1e874639488260795567337452b06292d1515bea12
valkey-cluster:
  enabled: false
valkey:
  enabled: false
postgresql-ha:
  enabled: false
postgresql:
  enabled: false
persistence:
  enabled: true
  size: 5Gi
strategy:
  type: Recreate
service:
  http:
    type: NodePort
    port: 31800
    nodePort: 30080
  ssh:
    type: ClusterIP
gitea:
  admin:
    existingSecret: gitea-admin
  config:
    database:
      DB_TYPE: sqlite3
    server:
      DOMAIN: gitea.localhost
      ROOT_URL: https://gitea.localhost:34443/
      HTTP_PORT: 3000
      DISABLE_SSH: true
    service:
      DISABLE_REGISTRATION: true
    actions:
      ENABLED: true
      RUN_RETENTION_DAYS: 0
    cache:
      ADAPTER: memory
    session:
      PROVIDER: memory
    queue:
      TYPE: level
    security:
      EGRESS_MODE: lax
      ALLOWED_HOST_LIST: webhook.platform.svc.cluster.local
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: '2'
    memory: 1Gi
